### PR TITLE
Big update of i18n and l15n.

### PR DESCRIPTION
**Pull request by BenjaminGalliot**
Related to https://github.com/CoEDL/elpis/pull/133

### CODE REVIEW

**Review by nicklambourne — CHANGES_REQUESTED** [review]
This looks fantastic, just needs a few things:

- A GUI mechanism to set or change the language (perhaps up near engine selection?)
- Default set to English, if possible. Most of our current users (and the dev team) are English-speaking, so I think this makes sense at this stage (should that change I'd be happy to reevaluate).

**Review by nicklambourne — CHANGES_REQUESTED** [review]
Just a couple of small things.

**Comment by BenjaminGalliot** [comment]
I added a small code to autodetect the best language (defaulting to English for most users). I don’t have the technical skills to make a GUI button, but I prepared the best I could!

By the way, the French default was a mistake!

**Review by nicklambourne — APPROVED** [review]
👌

**Review by nicklambourne — APPROVED** [review]

**Pull request merged**
